### ISSUE TITLE
Persist key by external provider

### ISSUE THREAD

**Issue by jasonho215** [WeAreBeep/FrontLineLive#33]
Since we have containerised the ASP.NET server and have changed the hosted environment to be Linux, we need to manage the key by our own.

```
2021-03-21T22:11:37.369651644Z [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[7]
2021-03-21T22:11:37.369710245Z       Error unprotecting the session cookie.
2021-03-21T22:11:37.370422650Z System.Security.Cryptography.CryptographicException: The key {8bc1cea5-0d61-444a-be5e-9f867b14296e} was not found in the key ring.
2021-03-21T22:11:37.370436350Z    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2021-03-21T22:11:37.371048055Z    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
2021-03-21T22:11:37.371061055Z    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2021-03-21T22:11:37.371080955Z    at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

Reference
- https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x&view=aspnetcore-5.0#persisting-keys-when-hosting-in-a-docker-container
- https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-5.0&tabs=visual-studio

We may use
- Database, or
- Redis

**Comment by jasonho215** [comment]
Closed via 20faebf
